# Simple Hyprland Ziggy terminal palette.

foreground              #cccccc
background              #222222
selection_foreground    #222222
selection_background    #9e9e9e

cursor                  #eeeeee
cursor_text_color       #222222
url_color               #6688ff

active_border_color     #6688ff
inactive_border_color   #4e4e4e
bell_border_color       #ff8080

active_tab_foreground   #222222
active_tab_background   #6688ff
inactive_tab_foreground #cccccc
inactive_tab_background #2d2d2d
tab_bar_background      #1e1e1e

color0  #353535
color1  #ff8080
color2  #22ee55
color3  #f7a41d
color4  #6688ff
color5  #b1a0f8
color6  #21edba
color7  #cccccc

color8  #808080
color9  #ff8080
color10 #22ee55
color11 #f7a41d
color12 #6688ff
color13 #b1a0f8
color14 #21edba
color15 #eeeeee
